config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:new, :index, :create, :show, :destroy] do
    resources :reviews, only: [:create, :destroy]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }, presence: true

  def destroy
    self.reviews.each do |review|
      review.destroy
    end
    super
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, presence: true, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Yelp !" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for (@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES, prompt: "Choisis un type" %>
  <div class="text-center">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1 class="text-center">Les restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <div class="card">
    <%= link_to restaurant_path(restaurant), class: "fill-div" do %>
      <%= restaurant.name %>
      <%= link_to restaurant_path(restaurant), method: :delete do %>
        <i class="fa fa-times pull-right" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
<% end %>
<br>
<div class="text-center">
<%= link_to "Créer un restaurant", new_restaurant_path, class: "btn btn-danger" %>
</div>

app/views/restaurants/new.html.erb
<h1>Créer un restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1 class="text-center"><%= @restaurant.name %></h1>
<p>Addresse : <%= @restaurant.address %></p>
<p>Téléphone : <%= @restaurant.phone_number %></p>
<p>Type : <%= @restaurant.category %></p>

<div class="contenu">
  <% @restaurant.reviews.each do |review| %>
    <div class="card-review">
      <% review.rating.times do %>
        <i class='fa fa-star' aria-hidden='true'></i>
      <% end %>
      <% (5 - review.rating).times do %>
        <i class='fa fa-star-o' aria-hidden='true'></i>
      <% end %>
      &nbsp;&nbsp;&nbsp;<%= review.content %>
      <%= link_to restaurant_review_path(@restaurant, review), method: :delete do %>
        <i class="fa fa-times" aria-hidden="true"></i>
      <% end %>
    </div>
  <% end %>
</div>

<div class="wrapper">
  <%= render 'reviews/form' %>
</div>

<% content_for(:title) do %>
  <%= @restaurant.name %>
<% end %>

app/views/reviews/_form.html.erb
<div class="padded">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.error_notification %>
    <%= f.input :content %>
    <%= f.hidden_field :rating %>
    <i class='fa fa-star rating' id="1" aria-hidden='true'></i>
    <i class='fa fa-star rating' id="2" aria-hidden='true'></i>
    <i class='fa fa-star rating' id="3" aria-hidden='true'></i>
    <i class='fa fa-star rating' id="4" aria-hidden='true'></i>
    <i class='fa fa-star rating' id="5" aria-hidden='true'></i>
    <div class="text-center">
      <%= f.button :submit, class: "btn btn-danger" %>
      <%= link_to "Menu", restaurants_path, class: "btn btn-primary text-center" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('.rating').on('click', function(){
      $('#review_rating').val(this.id)
    });
    $('.rating')
      .mouseover(function(){
        for (i = 1 ; i <= this.id ; i += 1){
          $('#' + i).addClass('rating-yellow');
        }
      }).mouseout(function(){
        $('.rating').removeClass('rating-yellow');
        var stars = $('#review_rating').val();
        for (i = 1 ; i <= stars ; i += 1){
          $('#' + i).addClass('rating-yellow');
        }
      });
  });
</script>